#!/bin/sh
COMMIT=$(git-rev-list -n 1 HEAD -- $(dirname $0))
VER=$(git-describe --tags $COMMIT 2>/dev/null)

echo $VER | sed -e 's/^v\?\([^-]\+\)-\(.*\)$/\1/' 
echo $VER | sed -e 's/^v\?\([^-]\+\)-\(.*\)$/\2/ ; s/-/\./g'
